version: "3.9"
services:
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "tinkle-api"
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:
